#!/bin/bash
# Download the Singularity container
# as created by https://github.com/richelbilderbeek/singularity_example_10
#
# Usage, local:
#
#    ./1_download_container
#
# Usage, Peregrine:
#
#    sbatch 1_download_container
#
#
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=1_download_container
#SBATCH --output=1_download_container.log

singularity pull library://richelbilderbeek/default/singularity_example_10