#!/bin/bash
# Download the Singularity container
# as created by https://github.com/richelbilderbeek/singularity_example_10
#
# Usage, local:
#
#    ./1_download_container
#
# Usage, Peregrine:
#
#    sbatch 1_download_container
#
#
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=1_download_mycobacterium_proteome
#SBATCH --output=1_download_mycobacterium_proteome.log

singularity exec singularity_example_10.sif \
  esearch -db assembly -query '("Mycobacterium"[Organism] OR mycobacterium[All Fields]) AND (latest[filter] AND "complete genome"[filter] AND all[filter] NOT anomalous[filter])' | elink -target nuccore -name assembly_nuccore_refseq | elink -target protein | efetch -db protein -format fasta > mycobacterium.faa 
