#!/bin/bash
# Make a database based on the short proteome
#
# Usage, local:
#
#    ./5_create_relatives_short
#
# Usage, Peregrine:
#
#    sbatch 5_create_relatives_short
#
#
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=5_create_relatives_short
#SBATCH --output=5_create_relatives_short.log
singularity exec singularity_example_10.sif \
  blastp -query mycobacterium_short.faa -db mycobacterium_short.faa -out short_vs_short.xml -outfmt 5
